name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: run tests
        run: go test ./internal/...

  build:
    name: Build - Deploy Docker image to Registry
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} --password ${{ secrets.REGISTRY_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ steps.string.outputs.lowercase }}/person-app:latest -f ./deploy/Dockerfile .      

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ steps.string.outputs.lowercase }}/person-app:latest