name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: run tests
        run: go test ./internal/...

  build:
    name: Build and Push Docker image to Registry
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} --password ${{ secrets.REGISTRY_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ steps.string.outputs.lowercase }}/person-app:latest -f ./deploy/Dockerfile .      

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ steps.string.outputs.lowercase }}/person-app:latest

  deploy:
    name: Deploy to remote server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - uses: actions/checkout@v4

      - name: Connect to remote server
        uses: appleboy/ssh-action@v1.0.3
        env:
          USER_REGISTRY: ${{ github.actor }}
          PASS_REGISTRY: ${{ secrets.REGISTRY_TOKEN }}
          ACTION_REGISTRY: ${{ steps.string.outputs.lowercase }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            docker login ghcr.io -u $USER_REGISTRY --password $PASS_REGISTRY
            (docker stop person-app && docker rm person-app || true) && \
            docker run -d -p 8000:8000 --name person-app --env-file .env --restart=always ghcr.io/$ACTION_REGISTRY/person-app:latest